### ISSUE TITLE
STYLE GUIDE 

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#10]
Create the typography and iconography of  the style guide.

**Comment by Bank-Taylor** [comment]
Task done

**Comment by arielcyril** [comment]
I worked on the style guides and  created the buttons. Below is the link to it:
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/Chunk-file-proj_team_49?node-id=1506%3A4324
