### ISSUE TITLE
USER RESEARCH 1

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#11]
All team members assigned to this task would be working on the following; 
1. The research plan
2. Writing an interview Script
3. Writing survey questions
4. Conducting Interviews

**Comment by Oziehkika** [comment]
done!!!

**Comment by Oluwatoby1** [comment]
Research plan has been created, screener survey has been sent out and we've received response.

**Comment by Eva-jacobs** [comment]
well done

**Comment by Eva-jacobs** [comment]
https://www.figma.com/file/JiJZTqbYAI3J5FAa8coohr/chunk-file-49-emphathy-map?node-id=0%3A1
User research 1 is done. Our ideal users are web developers and data analysts
