### ISSUE TITLE
STYLE GUIDE

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#12]
Create the color styling and the desktop grid system

**Comment by Eva-jacobs** [comment]
I am done with the desktop grid.

**Comment by Eva-jacobs** [comment]
All task done

**Comment by gidi287** [comment]
style guide done

**Comment by gidi287** [comment]
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/CHUNK_FILE?node-id=105%3A2

**Comment by gidi287** [comment]
the style guide gives us the basic guide to follow when designing the web screens
