### ISSUE TITLE
USER RESEARCH 2

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#13]
All team mates assigned to this task are to do the following;
1. Analyze your interview feedback to come up with an empathy map
2. Draw up a user persona
3. Brainstorm and prioritize ideas
4. Come up with features for the Chunk_it web application.

**Comment by Oziehkika** [comment]
Analysis of the interview is in progress

**Comment by Eva-jacobs** [comment]
Victor, please join the figma board....lets conclude.

**Comment by Oluwatoby1** [comment]
Holla Team.

**Comment by Eva-jacobs** [comment]
https://www.figma.com/file/JiJZTqbYAI3J5FAa8coohr/chunk-file-49-emphathy-map?node-id=0%3A1

Identified pain points, brain storming and ideation completed. Flow chart done but will be modified.
