### ISSUE TITLE
LANDING PAGE

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#14]
Create the wire frame and the low fidelity of the landing page.

**Comment by Eva-jacobs** [comment]
Also create the high fidelity. Please let us stick with the style guide strictly.

**Comment by gidi287** [comment]
Wireframe, low-fi and high-fidelity all done

**Comment by Eva-jacobs** [comment]
well done.

**Comment by Dollypizzle21** [comment]
all done

**Comment by Dollypizzle21** [comment]
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/CHUNK_FILE?node-id=0%3A1
