### ISSUE TITLE
LOG IN PAGE

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#15]
Create the log in page (wire frame, low fidelity and high fidelity). 
Follow the style guide strictly please.

**Comment by JessieRaph** [comment]
Task is currently in progress

**Comment by Istudioo** [comment]
Task is currently in progress

**Comment by Eva-jacobs** [comment]
okay, well done

**Comment by JessieRaph** [comment]
> Task is currently in progress

My partner and I are done with this task

**Comment by JessieRaph** [comment]
> okay, well done

My partner and I are done with this task

**Comment by JessieRaph** [comment]
> okay, well done

My partner and I are done with this task

**Comment by JessieRaph** [comment]
> okay, well done

My partner and I are done with this task

**Comment by Eva-jacobs** [comment]
Great
