### ISSUE TITLE
SIGN UP PAGE

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#16]
Create the sign up page(wire frame, low fidelity and high fidelity) and please strictly follow the style guide. Thanks

**Comment by ola123s** [comment]
done

**Comment by Eva-jacobs** [comment]
okay, great

**Comment by ola123s** [comment]
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/CHUNK_FILE?node-id=0%3A1

**Comment by Richella-rich** [comment]
yea..i and Sheriff worked on the sign up page

**Comment by Richella-rich** [comment]
Hi Eva..i am also done with the contact us page but its not reflecting here on github
