### ISSUE TITLE
DASHBOARD

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#17]
To create the dashboard for the chunk_it product, showing the following features, 
1. Upload
2. Recently chunked files
3. A side menu e.t.c

**Comment by Eva-jacobs** [comment]
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/CHUNK_FILE?node-id=0%3A1
The wireframe of the dash board clearly guides the design.

**Comment by gidi287** [comment]
the dashboard High-fi and low-fi are all done and completed
here is the link below 
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/Chunk-file-proj_team_49?node-id=0%3A1
