### ISSUE TITLE
FAQ PAGE (FREQUENTLY ASKED QUESTIONS)

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#18]
Design the page showing the frequently asked questions.

**Comment by Bank-Taylor** [comment]
Task in progress.

**Comment by ola123s** [comment]
IN progress

**Comment by Eva-jacobs** [comment]
great job guys

**Comment by Richella-rich** [comment]
hello team_49

**Comment by Eva-jacobs** [comment]
Hello Richella... What's up?

**Comment by Richella-rich** [comment]
> 

Hi Eva..i am cool..working on figma..just wanted to check on this space

**Comment by Eva-jacobs** [comment]
Lol, okay. Cool. Would've joined you guys on dogma, my system is off.

**Comment by ola123s** [comment]
no qualms  boss

**Comment by ola123s** [comment]
done @Eva-jacobs

**Comment by ola123s** [comment]
> done @Eva-jacobs

https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/CHUNK_FILE?node-id=0%3A1

**Comment by Bank-Taylor** [comment]
done @Eva-jacobs

https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/CHUNK_FILE?node-id=0%3A1

**Comment by Eva-jacobs** [comment]
well done
