### ISSUE TITLE
ACCOUNT SETTINGS

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#22]
The account settings page should have details of the user and basic reset options.

**Comment by Eva-jacobs** [comment]
Well done. Alright

**Comment by JessieRaph** [comment]
Done with this task

https://www.figma.com/file/yEaA3KGEgJwKdTvJJLaVKg/Proj-team-49-work-board?node-id=17%3A12779
