### ISSUE TITLE
Style Guide 

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#60]
Please create the spacers.

**Comment by Jemimahhhh** [comment]
Done. https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/Chunk-file-proj_team_49?node-id=105%3A2

**Comment by Jemimahhhh** [comment]
Link to spacer task...  https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/Chunk-file-proj_team_49?node-id=1506%3A4444
