### ISSUE TITLE
Create the contact us page

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#82]
Please work on the contact us page

**Comment by Richella-rich** [comment]
i am done with the contact us page. Thank you.

**Comment by Richella-rich** [comment]
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/Chunk-file-proj_team_49?node-id=0%3A1

here is the link

**Comment by Oziehkika** [comment]
i am updating the meet the team section that was later added during our meeting
