### ISSUE TITLE
Create the screens for the dashboard

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#84]
Kindly create the dashboard and the other screens that would serve as an overlay on the dashboard

**Comment by gidi287** [comment]
all the dashboard screens are now completely done

**Comment by gidi287** [comment]
here is the link 
https://www.figma.com/file/avaD8B1hOxxmzSQ1Qx5A0m/Chunk-file-proj_team_49?node-id=0%3A1
