### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by Eva-jacobs** [zuri-training/Chunk-File_Proj_team_49#91]
Kindly design the about us page. 
It should contain a brief documentation (what is a csv and json file)
A meet the team section beneath the page 
Detailed how to use page.

**Comment by Oziehkika** [comment]
the wireframes and low fidelity designs have been completed
 currently working on the high fidelity screens

**Comment by Richella-rich** [comment]
The about us page is done

**Comment by Oziehkika** [comment]
https://www.figma.com/file/yEaA3KGEgJwKdTvJJLaVKg/Proj-team-49-work-board?node-id=17%3A16707

based on our last conversations i had to include a new section the meet our team section
